### ISSUE TITLE
Error in 1.20.1

### ISSUE THREAD

**Issue by noiverre** [apatuka/oraxenuifilter#1]
Error log:
```
[10:08:06 WARN]: Unexpected exception while parsing console command "mi reload all"
org.bukkit.command.CommandException: Unhandled exception executing command 'mi' in plugin MMOItems v6.9.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1003) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:966) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:504) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:451) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: io/th0rgal/oraxen/items/OraxenItems
        at me.apatuka.OraxenUIFilter.Hooks.OraxenUIFilterHook.isValid(OraxenUIFilterHook.java:54) ~[OraxenUIFilter.jar:?]
        at io.lumine.mythic.lib.api.crafting.uimanager.ProvidedUIFilter.isValid(ProvidedUIFilter.java:140) ~[MythicLib-1.6.1.jar:?]
        at net.Indyuce.mmoitems.api.crafting.ingredient.VanillaIngredient.<init>(VanillaIngredient.java:69) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.api.crafting.LoadedCraftingObject.load(LoadedCraftingObject.java:46) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.manager.CraftingManager.getIngredient(CraftingManager.java:148) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.api.crafting.recipe.Recipe.<init>(Recipe.java:55) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.api.crafting.recipe.CraftingRecipe.<init>(CraftingRecipe.java:37) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.api.crafting.CraftingStation.loadRecipe(CraftingStation.java:188) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.api.crafting.CraftingStation.<init>(CraftingStation.java:51) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.manager.CraftingManager.reload(CraftingManager.java:104) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.command.mmoitems.ReloadCommandTreeNode.reloadStations(ReloadCommandTreeNode.java:96) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.command.mmoitems.ReloadCommandTreeNode.lambda$new$0(ReloadCommandTreeNode.java:23) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.command.mmoitems.ReloadCommandTreeNode$SubReloadCommandTreeNode.execute(ReloadCommandTreeNode.java:44) ~[MMOItems-6.9.4 (1).jar:?]
        at io.lumine.mythic.lib.command.api.CommandTreeRoot.onCommand(CommandTreeRoot.java:42) ~[MythicLib-1.6.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: io.th0rgal.oraxen.items.OraxenItems
        at me.apatuka.OraxenUIFilter.Hooks.OraxenUIFilterHook.isValid(OraxenUIFilterHook.java:54) ~[OraxenUIFilter.jar:?]
        at io.lumine.mythic.lib.api.crafting.uimanager.ProvidedUIFilter.isValid(ProvidedUIFilter.java:140) ~[MythicLib-1.6.1.jar:?]
        at net.Indyuce.mmoitems.api.crafting.ingredient.VanillaIngredient.<init>(VanillaIngredient.java:69) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.api.crafting.LoadedCraftingObject.load(LoadedCraftingObject.java:46) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.manager.CraftingManager.getIngredient(CraftingManager.java:148) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.api.crafting.recipe.Recipe.<init>(Recipe.java:55) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.api.crafting.recipe.CraftingRecipe.<init>(CraftingRecipe.java:37) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.api.crafting.CraftingStation.loadRecipe(CraftingStation.java:188) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.api.crafting.CraftingStation.<init>(CraftingStation.java:51) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.manager.CraftingManager.reload(CraftingManager.java:104) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.command.mmoitems.ReloadCommandTreeNode.reloadStations(ReloadCommandTreeNode.java:96) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.command.mmoitems.ReloadCommandTreeNode.lambda$new$0(ReloadCommandTreeNode.java:23) ~[MMOItems-6.9.4 (1).jar:?]
        at net.Indyuce.mmoitems.command.mmoitems.ReloadCommandTreeNode$SubReloadCommandTreeNode.execute(ReloadCommandTreeNode.java:44) ~[MMOItems-6.9.4 (1).jar:?]
        at io.lumine.mythic.lib.command.api.CommandTreeRoot.onCommand(CommandTreeRoot.java:42) ~[MythicLib-1.6.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

![image](https://github.com/apatuka/oraxenuifilter/assets/77881970/b8ff8c46-43ec-4cd8-89ad-938fbcb893eb)

Config:
```
# Station recipes
recipes:
    test-oraxen:
        output:
            type: ARMOR
            id: STEEL_HELMET
            amount: 1
        crafting-time: 7
        conditions:
        - level{level=8}
        - placeholder{placeholder="%mcmmo_level_mining%~>~100"}
        ingredients:
        - vanilla{type="ox orichalcum_ore ~",amount=6,display="Orichalcum Ore"}
 ```

```
orichalcum_ore:
  displayname: <white>Orichalcum Ore
  material: DIAMOND
  Pack:
    generate_model: false
    model: block/orichalcum_ore
    custom_model_data: 515
  Mechanics:
    noteblock:
      block_sounds:
        place_sound: block.stone.place
        break_sound: block.stone.break
        hit_sound: block.stone.hit
        step_sound: block.stone.step
        fall_sound: block.stone.fall
        volume: 0.8
        pitch: 0.8
      custom_variation: 515
      model: block/orichalcum_ore
      hardness: 10
      drop:
        silktouch: false
        fortune: false
        minimal_type: IRON
        best_tools:
        - PICKAXE
        loots:
        - oraxen_item: orichalcum_ore
          probability: 1.0
```

**Comment by noiverre** [comment]
I don't have ItemsAdder installed, only Oraxen

**Comment by apatuka** [comment]
Hello, looks like something changed on Oraxen API, will check this.

Thank you.

**Comment by apatuka** [comment]
https://github.com/apatuka/oraxenuifilter/releases/download/untagged-bb6814bbd1b86c071c04/OraxenUIFilter.jar

Please check if this is working for you. Thank you.

**Comment by noiverre** [comment]
Sorry, but I can't open the link, it's 404 error

**Comment by apatuka** [comment]
Oh, 

I just pushed an update on the spigot website 
https://www.spigotmc.org/resources/mmoitems-oraxenuifilter-itemsadderuifilter.107881/
